version = 0.1
[default.deploy.parameters]
stack_name = "foodatlas-automated-pipeline"
resolve_s3 = true
s3_prefix = "foodatlas-automated-pipeline"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
